version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Handlebars.Net
    versions:
    - 2.0.4
    - 2.0.5
    - 2.0.6
